project:
  type: default
  render:
    - dashboard/index.qmd

format:
  html:
    theme: flatly
    css: dashboard/styles.css
    page-layout: full
    toc: false
    lang: es
    code-fold: false
    code-tools: false

execute:
  echo: false
  warning: false

jupyter: python3