project:
  type: website
  render:
    - dashboard/*.qmd

website:
  title: "HackODS · Pumitas Prime"
  navbar:
    left:
      - text: "Inicio"
        file: dashboard/index.qmd
      - text: "Análisis ODS 4 vs ODS 8"
        file: dashboard/correlacion8y4.qmd

format:
  html:
    theme: flatly
    css: dashboard/styles.css
    page-layout: full
    toc: false
    lang: es
    code-fold: false
    code-tools: false

execute:
  echo: false
  warning: false

jupyter: python3