/****** Scripts para generar la estructura de la base de datos ******/
USE [master]
GO
-- CAMBIAR LA RUTA DONDE DESEA GUARDAR LA BASE DE DATOS (.mdf) Y EL ARCHIVO DE LOGS (.logs)
CREATE DATABASE [ODS] ON  PRIMARY 
( NAME = N'ODS', FILENAME = N'D:\ODSBD\ODS.mdf' , SIZE = 4038656KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
LOG ON 
( NAME = N'ODS_log', FILENAME = N'D:\ODSBD\ODS.ldf' , SIZE = 719296KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ODS] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ODS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ODS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ODS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ODS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ODS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ODS] SET ARITHABORT OFF 
GO

ALTER DATABASE [ODS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ODS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ODS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ODS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ODS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ODS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ODS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ODS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ODS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ODS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ODS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ODS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ODS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ODS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ODS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ODS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ODS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ODS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ODS] SET  READ_WRITE 
GO

ALTER DATABASE [ODS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ODS] SET  MULTI_USER 
GO

ALTER DATABASE [ODS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ODS] SET DB_CHAINING OFF 
GO
