/****** Script para Insertar Datos en el indicador 9.c.2 en el Esquema ManV2 ******/

USE [ODS]
GO
/****** Arbol ******/
INSERT [ManV2].[Arbol] ([arbClave], [arbClaveInd], [arbClaveFT], [arbClaveDescrip], [arbClaveMetadato]) VALUES (N'ODS0020',	0	,	0	,	14	,	10	)
INSERT [ManV2].[Arbol] ([arbClave], [arbClaveInd], [arbClaveFT], [arbClaveDescrip], [arbClaveMetadato]) VALUES (N'ODS00200005',	0	,	0	,	452	,	0	)
INSERT [ManV2].[Arbol] ([arbClave], [arbClaveInd], [arbClaveFT], [arbClaveDescrip], [arbClaveMetadato]) VALUES (N'ODS002000050015',	382	,	258	,	1241	,	0	)

/****** Metadato ******/
INSERT [ManV2].[Metadato] ([metClave], [metDescrip], [metDescripIng]) VALUES (	10	, N'"Si se hace bien, la agricultura, la silvicultura y las piscifactorías pueden suministrarnos comida nutritiva para todos y generar ingresos decentes, mientras se apoya el desarrollo de las gentes del campo y la protección del medio ambiente. Pero ahora mismo, nuestros suelos, agua, océanos, bosques y nuestra biodiversidad están siendo rápidamente degradados. El cambio climático está poniendo mayor presión sobre los recursos de los que dependemos y aumentan los riesgos asociados a desastres tales como sequías e inundaciones. Muchas campesinas y campesinos ya no pueden ganarse la vida en sus tierras, lo que les obliga a emigrar a las ciudades en busca de oportunidades. Necesitamos una profunda reforma del sistema mundial de agricultura y alimentación si queremos nutrir a los 925 millones de hambrientos que existen actualmente y los dos mil millones adicionales de personas que vivirán en el año 2050. El sector alimentario y el sector agrícola ofrecen soluciones claves para el desarrollo y son vitales para la eliminación del hambre y la pobreza."  Fuente: http://www.un.org/sustainabledevelopment/es/hunger/ (consultado el 3 de junio de 2016).', N'"It is time to rethink how we grow, share and consume our food. If done right, agriculture, forestry and fisheries can provide nutritious food for all and generate decent incomes, while supporting people-centred rural development and protecting the environment. Right now, our soils, freshwater, oceans, forests and biodiversity are being rapidly degraded. Climate change is putting even more pressure on the resources we depend on, increasing risks associated with disasters such as droughts and floods. Many rural women and men can no longer make ends meet on their land, forcing them to migrate to cities in search of opportunities. A profound change of the global food and agriculture system is needed if we are to nourish today’s 795 million hungry and the additional 2 billion people expected by 2050. The food and agriculture sector offers key solutions for development, and is central for hunger and poverty eradication."  Source: http://www.un.org/sustainabledevelopment/hunger/ (consulted on June 3, 2016).')

/****** Descripcion ******/

--INSERT [ManV2].[Descripcion] ([desClave], [desDescrip], [desAbrevia], [desCodigo], [desDescripIng], [desAbreviaIng], [desCodigoIng]) VALUES (	258	,N'Población total',N'',N'',N'Total population',N'',N'')
INSERT [ManV2].[Descripcion] ([desClave], [desDescrip], [desAbrevia], [desCodigo], [desDescripIng], [desAbreviaIng], [desCodigoIng]) VALUES (	452	,N'De aquí a 2030, poner fin al hambre y asegurar el acceso de todas las personas, en particular los pobres y las personas en situaciones de vulnerabilidad, incluidos los niños menores de 1 año, a una alimentación sana, nutritiva y suficiente durante todo el año',N'',N'Meta 2.1',N'By 2030, end hunger and ensure access by all people, in particular the poor and people in vulnerable situations, including infants, to safe, nutritious and sufficient food all year round',N'',N'Target 2.1')
INSERT [ManV2].[Descripcion] ([desClave], [desDescrip], [desAbrevia], [desCodigo], [desDescripIng], [desAbreviaIng], [desCodigoIng]) VALUES (	1241	,N'Proporción de la población con inseguridad alimentaria moderada o severa (carencia por acceso a la alimentación), desglosada por sexo y edad',N'',N'2.1.2',N'Proportion of the population with moderate or severe food insecurity (lack of access to food), disaggregated by sex and age',N'',N'2.1.2')
-- ANC faltaba para el indicador 2.1.2
INSERT [ManV2].[Descripcion] ([desClave], [desDescrip], [desAbrevia], [desCodigo], [desDescripIng], [desAbreviaIng], [desCodigoIng]) VALUES (978,N'Población con inseguridad alimentaria moderada o severa','','',N'Population with moderate or severe food insecurity','','')

/****** Enlace ******/
INSERT [ManV2].[Enlace] ([enlClavePalabra], [enlClaveDescrip]) VALUES (	44	,	1241	)
INSERT [ManV2].[Enlace] ([enlClavePalabra], [enlClaveDescrip]) VALUES (	45	,	1241	)
INSERT [ManV2].[Enlace] ([enlClavePalabra], [enlClaveDescrip]) VALUES (	51	,	1241	)
INSERT [ManV2].[Enlace] ([enlClavePalabra], [enlClaveDescrip]) VALUES (	52	,	1241	)
INSERT [ManV2].[Enlace] ([enlClavePalabra], [enlClaveDescrip]) VALUES (	53	,	1241	)
INSERT [ManV2].[Enlace] ([enlClavePalabra], [enlClaveDescrip]) VALUES (	63	,	1241	)
INSERT [ManV2].[Enlace] ([enlClavePalabra], [enlClaveDescrip]) VALUES (	126	,	1241	)
INSERT [ManV2].[Enlace] ([enlClavePalabra], [enlClaveDescrip]) VALUES (	238	,	1241	)
INSERT [ManV2].[Enlace] ([enlClavePalabra], [enlClaveDescrip]) VALUES (	617	,	1241	)
INSERT [ManV2].[Enlace] ([enlClavePalabra], [enlClaveDescrip]) VALUES (	670	,	1241	)
INSERT [ManV2].[Enlace] ([enlClavePalabra], [enlClaveDescrip]) VALUES (	671	,	1241	)
INSERT [ManV2].[Enlace] ([enlClavePalabra], [enlClaveDescrip]) VALUES (	672	,	1241	)

/****** Lexico ******/
--INSERT [ManV2].[Lexico] ([lexPalabra], [lexClavePalabra]) values (N'PROPORCION',	44	)
--INSERT [ManV2].[Lexico] ([lexPalabra], [lexClavePalabra]) values (N'POBLACION',	45	)
--INSERT [ManV2].[Lexico] ([lexPalabra], [lexClavePalabra]) values (N'DECJLOCADA',	51	)
--INSERT [ManV2].[Lexico] ([lexPalabra], [lexClavePalabra]) values (N'CEJO',	52	)
INSERT [ManV2].[Lexico] ([lexPalabra], [lexClavePalabra]) values (N'EDAD',	53	)
INSERT [ManV2].[Lexico] ([lexPalabra], [lexClavePalabra]) values (N'ALINENTARIA',	63	)
INSERT [ManV2].[Lexico] ([lexPalabra], [lexClavePalabra]) values (N'ACCECO',	126	)
INSERT [ManV2].[Lexico] ([lexPalabra], [lexClavePalabra]) values (N'CARENCIA',	238	)
INSERT [ManV2].[Lexico] ([lexPalabra], [lexClavePalabra]) values (N'ALINENTACION',	617	)
INSERT [ManV2].[Lexico] ([lexPalabra], [lexClavePalabra]) values (N'INCEJURIDAD',	670	)
INSERT [ManV2].[Lexico] ([lexPalabra], [lexClavePalabra]) values (N'NODERADA',	671	)
INSERT [ManV2].[Lexico] ([lexPalabra], [lexClavePalabra]) values (N'CEBERA',	672	)

/****** EnlaceIng ******/
INSERT [ManV2].[EnlaceING] ([enlClavePalabraIng], [enlClaveDescripIng]) VALUES(	32	,	1241	)
INSERT [ManV2].[EnlaceING] ([enlClavePalabraIng], [enlClaveDescripIng]) VALUES(	33	,	1241	)
INSERT [ManV2].[EnlaceING] ([enlClavePalabraIng], [enlClaveDescripIng]) VALUES(	37	,	1241	)
INSERT [ManV2].[EnlaceING] ([enlClavePalabraIng], [enlClaveDescripIng]) VALUES(	38	,	1241	)
INSERT [ManV2].[EnlaceING] ([enlClavePalabraIng], [enlClaveDescripIng]) VALUES(	47	,	1241	)
INSERT [ManV2].[EnlaceING] ([enlClavePalabraIng], [enlClaveDescripIng]) VALUES(	115	,	1241	)
INSERT [ManV2].[EnlaceING] ([enlClavePalabraIng], [enlClaveDescripIng]) VALUES(	221	,	1241	)
INSERT [ManV2].[EnlaceING] ([enlClavePalabraIng], [enlClaveDescripIng]) VALUES(	593	,	1241	)
INSERT [ManV2].[EnlaceING] ([enlClavePalabraIng], [enlClaveDescripIng]) VALUES(	594	,	1241	)
INSERT [ManV2].[EnlaceING] ([enlClavePalabraIng], [enlClaveDescripIng]) VALUES(	595	,	1241	)
INSERT [ManV2].[EnlaceING] ([enlClavePalabraIng], [enlClaveDescripIng]) VALUES(	833	,	1241	)

/****** LexicoIng ******/
--INSERT [ManV2].[LexicoING] ([lexPalabraIng], [lexClavePalabraIng]) VALUES (N'PROPORTION',	32	)
--INSERT [ManV2].[LexicoING] ([lexPalabraIng], [lexClavePalabraIng]) VALUES (N'POPULATION',	33	)
--INSERT [ManV2].[LexicoING] ([lexPalabraIng], [lexClavePalabraIng]) VALUES (N'SEX',	37	)
INSERT [ManV2].[LexicoING] ([lexPalabraIng], [lexClavePalabraIng]) VALUES (N'AGE',	38	)
INSERT [ManV2].[LexicoING] ([lexPalabraIng], [lexClavePalabraIng]) VALUES (N'FOOD',	47	)
INSERT [ManV2].[LexicoING] ([lexPalabraIng], [lexClavePalabraIng]) VALUES (N'ACCESS',	115	)
INSERT [ManV2].[LexicoING] ([lexPalabraIng], [lexClavePalabraIng]) VALUES (N'LACK',	221	)
INSERT [ManV2].[LexicoING] ([lexPalabraIng], [lexClavePalabraIng]) VALUES (N'MODERATE',	593	)
INSERT [ManV2].[LexicoING] ([lexPalabraIng], [lexClavePalabraIng]) VALUES (N'SEVERE',	594	)
INSERT [ManV2].[LexicoING] ([lexPalabraIng], [lexClavePalabraIng]) VALUES (N'INSECURITY',	595	)
INSERT [ManV2].[LexicoING] ([lexPalabraIng], [lexClavePalabraIng]) VALUES (N'DISAGGREGATED',	833	)

/****** AtrIndicador ******/
INSERT [ManV2].[AtrIndicador] ([atrClaveInd], [atrFechaAct], [atrMeta], [atrDesMeta], [atrCalculo], [atrEstadisticos], [atrClaveEst], [atrFechaActIng], [atrDesMetaIng], [atrVisualizaMapa], [atrEtiPeriodo], [atrEtiCobTem], [atrEstado]) VALUES (	382	,N'11 de noviembre de 2019',NULL,N'',N'SV',N'N',	0,N'november 11th, 2019',N''	,	N'N',	NULL	,	NULL	,	N'PUB')
/****** EnlIndCal ******/
INSERT [ManV2].[EnlIndCal] ([eicCveInd], [eicCveInst], [eicFecAct], [eicCveNotaI], [eicCveNotaF], [eicFecActIng]) VALUES(	382	,	67	,N'Segundo semestre de 2021',	0	,	329	,N'Second semester of 2021')

/****** Institucion ******/
-- INSERT [ManV2].[Institucion] ([insClave], [insDescrip], [insURL], [insAbrevia], [insDescripIng], [insAbreviaIng]) VALUES (67, N'Consejo Nacional de Evaluación de la Política de Desarrollo Social (CONEVAL).', N'http://www.coneval.org.mx/', N'CONEVAL',N'Consejo Nacional de Evaluación de la Política de Desarrollo Social (CONEVAL).',N'CONEVAL')

/****** EnlIndGra ******/
INSERT [ManV2].[EnlIndGra] ([eigCveInd], [eigCveGra], [eigSeccion]) VALUES (	382	,	1	,N'E')
INSERT [ManV2].[EnlIndGra] ([eigCveInd], [eigCveGra], [eigSeccion]) VALUES (	382	,	2	,N'M')
INSERT [ManV2].[EnlIndGra] ([eigCveInd], [eigCveGra], [eigSeccion]) VALUES (	382	,	2	,N'T')
INSERT [ManV2].[EnlIndGra] ([eigCveInd], [eigCveGra], [eigSeccion]) VALUES (	382	,	6	,N'C')

/****** EnlIndTipo ******/
INSERT [ManV2].[EnlIndTipo] ([eitCveInd], [eitCveTipoInd], [eitOrden]) VALUES (	382	,N'G',	1	)

/****** EnlIndPCve ******/
INSERT [ManV2].[EnlIndPCve] ([eipcCveInd], [eipcCveDesPCve]) VALUES (	382	,	4	)

/****** DescripcionPCve ******/
INSERT [ManV2].[DescripcionPCve] ([dpcClave], [dpcDescrip], [dpcAbrevia], [dpcDescripIng], [dpcAbreviaIng]) VALUES (	4	,N'Hambre, desnutrición, malnutrición, programas de ayuda alimentaria, Escala Mexicana de Seguridad Alimentaria (EMSA), Cruzada Nacional Contra el Hambre',	NULL	,	NULL	,	NULL	)

/****** EnlacePCve ******/
INSERT [ManV2].[EnlacePCve] ([epcCvePCve], [epcCveDesPCve]) VALUES (	4	,	1	)
INSERT [ManV2].[EnlacePCve] ([epcCvePCve], [epcCveDesPCve]) VALUES (	4	,	24	)
INSERT [ManV2].[EnlacePCve] ([epcCvePCve], [epcCveDesPCve]) VALUES (	4	,	50	)
INSERT [ManV2].[EnlacePCve] ([epcCvePCve], [epcCveDesPCve]) VALUES (	4	,	51	)

/****** LexicoPCve ******/
INSERT [ManV2].[LexicoPCve] ([lpcPalabraCve], [lpcClavePalCve]) VALUES (N'PERCONAC',	4	)

/****** EnlacePCveIng ******/
--NO HAY DATOS

/****** EnlSerInd ******/
INSERT [ManV2].[EnlSerInd] ([esiClaveInd], [esiClaveSerie], [esiOrden]) VALUES (	382	,	854	,	1	)
INSERT [ManV2].[EnlSerInd] ([esiClaveInd], [esiClaveSerie], [esiOrden]) VALUES (	382	,	855	,	2	)
INSERT [ManV2].[EnlSerInd] ([esiClaveInd], [esiClaveSerie], [esiOrden]) VALUES (	382	,	856	,	3	)

/****** AtrSerie ******/
--Indicador 382
INSERT [ManV2].[AtrSerie] ([atsClaveSerie], [atsClaveDescrip], [atsClaveFre], [atsAAPrelim], [atsMMPrelim], [atsDDPrelim], [atsAAEst], [atsMMEst], [atsDDEst], [atsDecimales], [atsClaveNota], [atsClaveFT], [atsClaveFuente], [atsClaveUnidad], [atsTipo], [atsSalida], [atsAARev], [atsMMRev], [atsDDRev], [atsClaveAgrupaCob], [atsClaveAgrupaClas], [atsColMatriz], [atsColMatrizIng], [atsTipoGra], [atsInicio], [atsTipoCua]) VALUES (	854	,	1241	,	14	,	0	,	0	,	0	,	0	,	0	,	0	,	1	,	0	,	0	,	486	,	60	,N'R',	1	,	0	,	0	,	0	,N'0010',	110	,N'Periodo',N'Period',	NULL	,	2008	,N'ACl')
INSERT [ManV2].[AtrSerie] ([atsClaveSerie], [atsClaveDescrip], [atsClaveFre], [atsAAPrelim], [atsMMPrelim], [atsDDPrelim], [atsAAEst], [atsMMEst], [atsDDEst], [atsDecimales], [atsClaveNota], [atsClaveFT], [atsClaveFuente], [atsClaveUnidad], [atsTipo], [atsSalida], [atsAARev], [atsMMRev], [atsDDRev], [atsClaveAgrupaCob], [atsClaveAgrupaClas], [atsColMatriz], [atsColMatrizIng], [atsTipoGra], [atsInicio], [atsTipoCua]) VALUES (	855	,	978	,	14	,	0	,	0	,	0	,	0	,	0	,	0	,	2	,	0	,	0	,	0	,	239	,N'I',	0	,	0	,	0	,	0	,N'0010',	110	,N'Periodo',N'Periodo',	NULL	,	2008	,N'ACl')
INSERT [ManV2].[AtrSerie] ([atsClaveSerie], [atsClaveDescrip], [atsClaveFre], [atsAAPrelim], [atsMMPrelim], [atsDDPrelim], [atsAAEst], [atsMMEst], [atsDDEst], [atsDecimales], [atsClaveNota], [atsClaveFT], [atsClaveFuente], [atsClaveUnidad], [atsTipo], [atsSalida], [atsAARev], [atsMMRev], [atsDDRev], [atsClaveAgrupaCob], [atsClaveAgrupaClas], [atsColMatriz], [atsColMatrizIng], [atsTipoGra], [atsInicio], [atsTipoCua]) VALUES (	856	,	258	,	14	,	0	,	0	,	0	,	0	,	0	,	0	,	2	,	0	,	0	,	0	,	239	,N'I',	0	,	0	,	0	,	0	,N'0010',	110	,N'Periodo',N'Period',	NULL	,	2008	,N'ACl')
 
--- SERIE ---- 
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	854	,	2008	,	0	,	0	,	21.9126547353641	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	854	,	2010	,	0	,	0	,	25.0777312814227	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	854	,	2012	,	0	,	0	,	23.5871731776537	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	854	,	2014	,	0	,	0	,	23.6266889407392	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	854	,	2016	,	0	,	0	,	20.2837819119666	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	854	,	2018	,	0	,	0	,	20.6118589297775	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	855	,	2008	,	0	,	0	,	24258.647	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	855	,	2010	,	0	,	0	,	28439.754	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	855	,	2012	,	0	,	0	,	27352.215	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	855	,	2014	,	0	,	0	,	27990.796	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	855	,	2016	,	0	,	0	,	24594.11	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	855	,	2018	,	0	,	0	,	25531.581	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	855	,	2008	,	0	,	0	,	11797.752	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	855	,	2010	,	0	,	0	,	13980.874	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	855	,	2012	,	0	,	0	,	13284	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	855	,	2014	,	0	,	0	,	13645.507	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	855	,	2016	,	0	,	0	,	11847.568	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	855	,	2018	,	0	,	0	,	12440.861	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	855	,	2008	,	0	,	0	,	12460.895	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	855	,	2010	,	0	,	0	,	14458.88	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	855	,	2012	,	0	,	0	,	14068.215	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	855	,	2014	,	0	,	0	,	14345.289	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	855	,	2016	,	0	,	0	,	12746.542	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	855	,	2018	,	0	,	0	,	13090.72	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	855	,	2008	,	0	,	0	,	10522.161	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	855	,	2010	,	0	,	0	,	11901.861	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	855	,	2012	,	0	,	0	,	11083.981	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	855	,	2014	,	0	,	0	,	10958.228	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	855	,	2016	,	0	,	0	,	9403.358	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	855	,	2018	,	0	,	0	,	9409.659	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	855	,	2008	,	0	,	0	,	13736.486	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	855	,	2010	,	0	,	0	,	16537.893	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	854	,	2018	,	0	,	0	,	18.2085420615286	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	854	,	2016	,	0	,	0	,	17.350167698692	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	854	,	2014	,	0	,	0	,	19.9766311440488	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	854	,	2012	,	0	,	0	,	19.917692214817	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	854	,	2010	,	0	,	0	,	21.4300791475423	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	854	,	2008	,	0	,	0	,	19.3043429752454	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	854	,	2018	,	0	,	0	,	20.1504532923077	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	854	,	2016	,	0	,	0	,	19.8307743177574	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	854	,	2014	,	0	,	0	,	22.7699287008066	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	854	,	2012	,	0	,	0	,	22.9591564688732	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	854	,	2010	,	0	,	0	,	24.6243830128366	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	854	,	2008	,	0	,	0	,	21.5918429919924	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	854	,	2018	,	0	,	0	,	21.005718535074	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	854	,	2016	,	0	,	0	,	20.5614967962693	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	854	,	2014	,	0	,	0	,	24.6498461632843	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	854	,	2012	,	0	,	0	,	24.0917887338949	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	854	,	2010	,	0	,	0	,	25.2696841435602	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	854	,	2008	,	0	,	0	,	22.0562373547826	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	854	,	2018	,	0	,	0	,	18.8105513492383	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	854	,	2016	,	0	,	0	,	18.4795317141361	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	854	,	2014	,	0	,	0	,	21.2587442891496	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	854	,	2012	,	0	,	0	,	20.8720860264497	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	854	,	2010	,	0	,	0	,	22.3149429829143	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	854	,	2008	,	0	,	0	,	19.4531099488374	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	854	,	2018	,	0	,	0	,	23.89717402248	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	854	,	2016	,	0	,	0	,	23.2563128481451	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	854	,	2014	,	0	,	0	,	27.5672789998886	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	854	,	2012	,	0	,	0	,	28.1579375428743	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	854	,	2010	,	0	,	0	,	29.4396635557766	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	854	,	2008	,	0	,	0	,	25.6921074867883	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	854	,	2018	,	0	,	0	,	20.3437364660985	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	854	,	2016	,	0	,	0	,	20.1404109009502	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	854	,	2014	,	0	,	0	,	23.3189012101526	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	854	,	2012	,	0	,	0	,	23.3975115759615	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	854	,	2010	,	0	,	0	,	24.6234286298073	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	854	,	2008	,	0	,	0	,	21.6496396488667	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	854	,	2018	,	0	,	0	,	20.4839262690281	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	854	,	2016	,	0	,	0	,	19.9627746727653	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	854	,	2014	,	0	,	0	,	23.3843004171676	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	854	,	2012	,	0	,	0	,	23.2322324314549	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	854	,	2010	,	0	,	0	,	25.0466837057072	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	854	,	2008	,	0	,	0	,	21.8431993024249	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	854	,	2018	,	0	,	0	,	20.4118067242961	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	854	,	2016	,	0	,	0	,	20.0544463470289	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	854	,	2014	,	0	,	0	,	23.3507375499039	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	854	,	2012	,	0	,	0	,	23.3169486568526	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	854	,	2010	,	0	,	0	,	24.8296966229216	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	854	,	2008	,	0	,	0	,	21.7433435351095	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	855	,	2012	,	0	,	0	,	16268.234	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	855	,	2014	,	0	,	0	,	17032.568	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	855	,	2016	,	0	,	0	,	15190.752	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	855	,	2018	,	0	,	0	,	16121.922	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	855	,	2008	,	0	,	0	,	8027.844	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	855	,	2010	,	0	,	0	,	9208.938	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	855	,	2012	,	0	,	0	,	8927.539	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	855	,	2014	,	0	,	0	,	9129.002	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	855	,	2016	,	0	,	0	,	7718.526	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	855	,	2018	,	0	,	0	,	8028.995	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	855	,	2008	,	0	,	0	,	16230.803	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	855	,	2010	,	0	,	0	,	19230.816	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	855	,	2012	,	0	,	0	,	18424.676	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	855	,	2014	,	0	,	0	,	18861.794	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	855	,	2016	,	0	,	0	,	16875.584	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	855	,	2018	,	0	,	0	,	17502.586	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	855	,	2008	,	0	,	0	,	1398.046	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	855	,	2010	,	0	,	0	,	1669.08	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	855	,	2012	,	0	,	0	,	1720.6	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	855	,	2014	,	0	,	0	,	1810.38	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	855	,	2016	,	0	,	0	,	1663.384	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	855	,	2018	,	0	,	0	,	1895.849	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	855	,	2008	,	0	,	0	,	22860.601	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	855	,	2010	,	0	,	0	,	26770.674	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	855	,	2012	,	0	,	0	,	25631.615	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	855	,	2014	,	0	,	0	,	26180.416	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	855	,	2016	,	0	,	0	,	22930.726	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	855	,	2018	,	0	,	0	,	23635.732	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	856	,	2008	,	0	,	0	,	111568.154	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	856	,	2010	,	0	,	0	,	114539.273	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	856	,	2012	,	0	,	0	,	117306.151	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	856	,	2014	,	0	,	0	,	119871.143	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	856	,	2016	,	0	,	0	,	122636.694	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110010',	856	,	2018	,	0	,	0	,	125082.416	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	856	,	2008	,	0	,	0	,	54011.099	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	856	,	2010	,	0	,	0	,	55819.262	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	856	,	2012	,	0	,	0	,	57179.18	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	856	,	2014	,	0	,	0	,	58353.283	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	856	,	2016	,	0	,	0	,	59348.303	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110020',	856	,	2018	,	0	,	0	,	60734.748	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	856	,	2008	,	0	,	0	,	57557.055	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	856	,	2010	,	0	,	0	,	58720.011	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	856	,	2012	,	0	,	0	,	60126.971	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	856	,	2014	,	0	,	0	,	61517.86	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	856	,	2016	,	0	,	0	,	63288.391	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110030',	856	,	2018	,	0	,	0	,	64347.668	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	856	,	2008	,	0	,	0	,	40954.838	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	856	,	2010	,	0	,	0	,	40427.979	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	856	,	2012	,	0	,	0	,	39363.611	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	856	,	2014	,	0	,	0	,	39750.851	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	856	,	2016	,	0	,	0	,	40433.572	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110040',	856	,	2018	,	0	,	0	,	39375.614	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	856	,	2008	,	0	,	0	,	70613.316	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	856	,	2010	,	0	,	0	,	74111.294	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	856	,	2012	,	0	,	0	,	77942.54	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	856	,	2014	,	0	,	0	,	80120.292	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	856	,	2016	,	0	,	0	,	82203.122	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110050',	856	,	2018	,	0	,	0	,	85706.802	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	856	,	2008	,	0	,	0	,	36397.16	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	856	,	2010	,	0	,	0	,	36442.632	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	856	,	2012	,	0	,	0	,	37056.356	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	856	,	2014	,	0	,	0	,	37034.722	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	856	,	2016	,	0	,	0	,	37538.736	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110060',	856	,	2018	,	0	,	0	,	38222.901	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	856	,	2008	,	0	,	0	,	75170.994	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	856	,	2010	,	0	,	0	,	78096.641	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	856	,	2012	,	0	,	0	,	80249.795	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	856	,	2014	,	0	,	0	,	82836.421	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	856	,	2016	,	0	,	0	,	85097.958	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110070',	856	,	2018	,	0	,	0	,	86859.515	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	856	,	2008	,	0	,	0	,	7242.132	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	856	,	2010	,	0	,	0	,	7788.492	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	856	,	2012	,	0	,	0	,	8638.551	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	856	,	2014	,	0	,	0	,	9062.489	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	856	,	2016	,	0	,	0	,	9587.135	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110080',	856	,	2018	,	0	,	0	,	10411.866	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	856	,	2008	,	0	,	0	,	104326.022	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	856	,	2010	,	0	,	0	,	106750.781	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	856	,	2012	,	0	,	0	,	108667.6	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	856	,	2014	,	0	,	0	,	110808.654	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	856	,	2016	,	0	,	0	,	113049.559	,	0	,	NULL	,	NULL	,	NULL	,N'00100010')
INSERT [ManV2].[Serie] ([serCveCobAgrupAnt], [serCveClaAgrup], [serClave], [serAADato], [serMMDato], [serDDDato], [serDato], [serNoDato], [serNota], [serLeyenda], [serLeyendaIng], [serCveCobAgrup]) VALUES (	NULL	,N'110090',	856	,	2018	,	0	,	0	,	114670.55	,	0	,	NULL	,	NULL	,	NULL	,N'00100010') 
 
/****** AgrupaCob ******/

-- INSERT [ManV2].[AgrupaCob] ([acoClave], [acoCveGeo], [acoCveDesGeo], [acoOrden], [acoClaveAnt]) VALUES (N'0010',NULL	,	1	,	NULL	,	NULL	)
--  INSERT [ManV2].[AgrupaCob] ([acoClave], [acoCveGeo], [acoCveDesGeo], [acoOrden], [acoClaveAnt]) VALUES (N'00100010',N'00',	1	,	NULL	,	NULL	)


/****** FichaTecnica ******/

INSERT [ManV2].[FichaTecnica] ([ftClave], [ftDefinicion], [ftAlgoritmo], [ftUnidad], [ftImportancia], [ftCobGeo], [ftPeriodo], [ftFecEsp], [ftObs], [ftDefinicionIng], [ftImportanciaIng], [ftObsIng], [ftFecEspIng], [ftDescripCal], [ftDescripCalIng], [ftOportunidad], [ftOportunidadIng], [ftCobGeoft], [ftAlgoritmoIng]) 
VALUES (258,N'La inseguridad alimentaria moderada o severa son los grados de inseguridad alimentaria que reflejan la existencia de limitaciones en la cantidad de alimentos en el hogar y experiencias de hambre en la alimentación de los integrantes de los hogares. La clasificación de la situación de seguridad o inseguridad alimentaria se hace con base en la Escala Mexicana de Seguridad Alimentaria (EMSA).',N'2_1_2_a_ES',0,N'El Indicador describe el  porcentaje de personas que han visto reducida la cantidad de alimentos y han experimentado episodios de hambre en su hogar. El indicador ha sido utilizado para evaluar el impacto de algunos programas de ayuda alimentaria que forman parte de la Cruzada Nacional Contra el Hambre.',NULL, 20,NULL,
N'A fin de contar con una medida que refleje con la mayor precisión posible la existencia de limitaciones significativas en el ejercicio del derecho a la alimentación, se considera en situación de carencia por acceso a la alimentación a los hogares que presenten un grado de inseguridad alimentaria moderada o severa.¬¬Las escalas de seguridad alimentaria evalúan aspectos como la preocupación por la falta de alimentos, los cambios en la calidad y cantidad de estos, e incluso las experiencias de hambre. Para el caso latinoamericano, un grupo de especialistas en nutrición ha venido desarrollando una adaptación de esta escala, la cual ha sido validada para el caso mexicano después de una serie de estudios y levantamientos de información en el país.¬¬¬<sup>*/</sup> La actualización del indicador está sujeta a la publicación de los microdatos por parte de INEGI.',N'Moderate or severe food insecurity is the degree of food insecurity that reflects the existence of limitations in the amount of food in the home and experiences of hunger in the food of the household members. The classification of the security situation or food insecurity is based on the Mexican Food Security Scale (EMSA).',N'The Indicator describes the percentage of people who have seen a reduced amount of food and experienced episodes of hunger in their home. The indicator has been used to evaluate the impact of some food aid programs that are part of the National Crusade Against Hunger.',N'In order to have a measure that reflects as accurately as possible the existence of significant limitations in the exercise of the right to food, it is considered in a situation of lack of access to food to households with a moderate degree of food insecurity. or severe.¬¬Food safety scales assess aspects such as concern about the lack of food, changes in the quality and quantity of food, and even experiences of hunger. For the Latin American case, a group of nutrition specialists has been developing an adaptation of this scale, which has been validated for the Mexican case after a series of studies and surveys of information in the country.¬¬<sup>*/</sup> The updating of the indicator is subject to the publication of microdata by INEGI.',
NULL,N'Se determina a partir de una distinción entre los hogares con población menor de dieciocho años y los hogares sin población menor de dieciocho años. Para el total de hogares donde no habitan menores de dieciocho años de edad se identifican aquellos en los que algún adulto, por falta de dinero o recursos, al menos: no tuvo una alimentación variada; dejó de desayunar, comer o cenar; comió menos de lo que debería comer; se quedaron sin comida; sintió hambre, pero no comió; o hizo sólo una comida o dejó de comer durante todo el día. En el caso del total de hogares donde habitan menores de dieciocho años de edad se identifican aquellos en los que por falta de dinero o recursos, tanto las personas mayores como las menores de dieciocho años: tuvieron una alimentación variada; comieron menos de lo necesario; se les disminuyeron las cantidades servidas en la comida; sintieron hambre, pero no comieron; o hicieron una comida o dejaron de comer durante todo el día.',N'It is determined from a distinction between households with a population under eighteen years of age and households without a population under eighteen years of age. For all households that do not live under eighteen years of age, those in which some adult, for lack of money or resources, at least: did not have a varied diet; He stopped having breakfast, lunch or dinner; he ate less than he should eat; they ran out of food; he felt hungry, but he did not eat; or did only one meal or stopped eating all day long. In the case of the total number of households inhabited by persons under eighteen years of age, those in which, for lack of money or resources, both the elderly and those under eighteen years of age were identified: had a varied diet; they ate less than necessary; the quantities served in the food were reduced; they felt hungry, but they did not eat; either they made a meal or they stopped eating all day long.',
N'1 año <sup>*/</sup>',N'1 year<sup>*/</sup>',24,N'2_1_2_a_EN')

/****** EnlFTMFte ******/
INSERT   [ManV2].[EnlFTMFte] ([effClave], [effClaveFue], [effOrden]) VALUES (	258	,	370	,	2	)
INSERT  [ManV2].[EnlFTMFte] ([effClave], [effClaveFue], [effOrden]) VALUES (	258	,	487	,	1	)

/****** Fuentes ******/
INSERT [ManV2].[Fuentes] ([fueClave], [fueDescrip], [fueDescripIng]) VALUES (	370	,N'Consejo Nacional de Evaluación de la Política de Desarrollo Social (CONEVAL). <a target="_blank" class="liga3" href="http://www.coneval.org.mx/Informes/Coordinacion/Publicaciones%20oficiales/MEDICION_MULTIDIMENSIONAL_SEGUNDA_EDICION.pdf"> Metodología para la medición multidimensional de la pobreza en México.</a> Fecha de consulta: 05 de agosto de 2019.',N'Consejo Nacional de Evaluación de la Política de Desarrollo Social (CONEVAL). <a target="_blank" class="liga3" href="http://www.coneval.org.mx/Informes/Coordinacion/Publicaciones%20oficiales/MEDICION_MULTIDIMENSIONAL_SEGUNDA_EDICION.pdf"> Metodología para la medición multidimensional de la pobreza en México.</a> Date of consultation: August 05, 2019.')
INSERT [ManV2].[Fuentes] ([fueClave], [fueDescrip], [fueDescripIng]) VALUES (	487	,N'Instituto Nacional de Estadística y Geografía (INEGI). Módulo de Condiciones Socioeconómicas de la Encuesta Nacional de Ingresos y Gastos de los Hogares (MCS-ENIGH) 2008-2014. <a target="_blank" class="liga3" href="https://www.inegi.org.mx/programas/mcs/2008/">https://www.inegi.org.mx/programas/mcs/2008/</a>y Modelo Estadístico para la Continuidad (MEC) del MCS-ENIGH 2016 y 2018. <a target="_blank" class="liga3" href="https://www.inegi.org.mx/investigacion/eash/2018/">https://www.inegi.org.mx/investigacion/eash/2018/</a>',N'Instituto Nacional de Estadística y Geografía (INEGI). Módulo de Condiciones Socioeconómicas de la Encuesta Nacional de Ingresos y Gastos de los Hogares (MCS-ENIGH) 2008-2014. <a target="_blank" class="liga3" href="https://www.inegi.org.mx/programas/mcs/2008/">https://www.inegi.org.mx/programas/mcs/2008/</a>and Modelo Estadístico para la Continuidad (MEC) del MCS-ENIGH 2016 y 2018. <a target="_blank" class="liga3" href="https://www.inegi.org.mx/investigacion/eash/2018/">https://www.inegi.org.mx/investigacion/eash/2018/</a>')

/****** ENLFTRRI ******/
INSERT [ManV2].[EnlFTRRI] ([efrClave], [efrClaveRI], [efrOrden]) VALUES (258, 132, 1)
INSERT [ManV2].[EnlFTRRI] ([efrClave], [efrClaveRI], [efrOrden]) VALUES (258, 133, 2)

/****** RefInter ******/
INSERT [ManV2].[RefInter] ([riClave], [riDescrip], [riDescripIng]) VALUES (132, N'Se emplea una escala de seguridad alimentaria basada en una propuesta de Pérez-Escamilla, Melgar-Quiñonez, Nord, Álvarez y Segall-Correa. Esta escala reconoce cuatro posibles niveles de inseguridad alimentaria: inseguridad alimentaria severa, inseguridad alimentaria moderada, inseguridad alimentaria leve y seguridad alimentaria.¬¬Para mayor detalle consultar:¬La <a target="_blank" class="liga3" href="http://www.coneval.gob.mx/Informes/Coordinacion/Publicaciones%20oficiales/MEDICION_MULTIDIMENSIONAL_SEGUNDA_EDICION.pdf">Metodología para la medición multidimensional de la pobreza en México.</a>',N'A food safety scale is used based on a proposal by Pérez-Escamilla, Melgar-Quiñonez, Nord, Álvarez y Segall-Correa. This scale recognizes four possible levels of food insecurity: severe food insecurity, moderate food insecurity, mild food insecurity and food security.¬¬For further details consult the <a target="_blank" class="liga3" href="http://www.coneval.gob.mx/Informes/Coordinacion/Publicaciones%20oficiales/MEDICION_MULTIDIMENSIONAL_SEGUNDA_EDICION.pdf">Methodology for the multidimensional measurement of poverty in Mexico</a>')
INSERT [ManV2].[RefInter] ([riClave], [riDescrip], [riDescripIng]) VALUES (133, N'Datos de CONEVAL sobre acceso a la alimentación: <a target="_blank" class="liga3" href="http://www.coneval.gob.mx/Medicion/Paginas/PobrezaInicio.aspx">http://www.coneval.gob.mx/Medicion/Paginas/PobrezaInicio.aspx</a>',N'CONEVAL data on access to food: <a target="_blank" class="liga3" href="http://www.coneval.gob.mx/Medicion/Paginas/PobrezaInicio.aspx">http://www.coneval.gob.mx/Medicion/Paginas/PobrezaInicio.aspx</a>')

/****** EnlFTRInst ******/
INSERT [ManV2].[EnlFTRInst] ([efiClave], [efiClaveInst], [efiOrden]) VALUES (258, 67, 1)

/****** EnlFTCon ******/
INSERT [ManV2].[EnlFTCon] ([efcClaveFT], [efcClaveCon], [efcOrden]) VALUES (258, 2, 1)

/****** Contacto ******/
--INSERT [ManV2].[Contacto] ([conClave], [conNombre], [conPuesto], [conTelefono], [conCorreo], [conDomicilio]) VALUES (2, N'Alida Marcela Gutiérrez Landeros', N'Directora Ejecutiva de Medición de Pobreza y Seguimiento de Indicadores',N'54 81 72 75 o 00, ext. 70075',N'amgutierrez@coneval.org.mx',N'Insurgentes Sur #810,¬Colonia Del Valle, C.P. 03100,¬Benito Juárez, Ciudad de México')
