/****** Script crear los Esquemas ******/

USE [ODS]
GO
CREATE SCHEMA [ManV2] AUTHORIZATION [ODS.owner]
GO
CREATE SCHEMA [PreV2] AUTHORIZATION [ODS.Update]
GO
CREATE SCHEMA [PubV2] AUTHORIZATION [ODS.Consulta]
GO

/****** Permiso por Esquemas ******/

-- ODS.Owner  default ManV2
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::[PreV2] TO [ODS.Owner]
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::[PubV2] TO [ODS.Owner]

-- ODS.Update  default PreV2
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::[ManV2] TO [ODS.Update]
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON SCHEMA::[PubV2] TO [ODS.Update]

-- ODS.Consulta  default PubV2
GRANT SELECT, EXECUTE ON SCHEMA::[ManV2] TO [ODS.Consulta]
GRANT SELECT, EXECUTE ON SCHEMA::[PreV2] TO [ODS.Consulta]